// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzeriaOnline.Data;

#nullable disable

namespace PizzeriaOnline.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250608013423_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("PizzeriaOnline.Models.Ingredientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PizzaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("PizzeriaOnline.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaImagen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Masa maestra, salsa secreta, aceitunas negras, morrón, elote, cebolla morada, pepperoni, piña, champiñones, romero, mozzarella",
                            Nombre = "Monumental",
                            RutaImagen = "/images/pizzas/monumental.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Masa maestra, salsa secreta, queso mozzarella, albhaca fresca.",
                            Nombre = "Macarena",
                            RutaImagen = "/images/pizzas/macarena.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Masa maestra, salsa secreta, piña, jamón, mozzarella",
                            Nombre = "Sevillana",
                            RutaImagen = "/images/pizzas/sevillana.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Masa maestra, salsa secreta, pepperoni , mozzarella",
                            Nombre = "Manoletina",
                            RutaImagen = "/images/pizzas/manoletina.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Masa maestra, salsa secreta, frijoles, elote, morrón, tocino, chorizo, rodajas de serrano",
                            Nombre = "Miura",
                            RutaImagen = "/images/pizzas/miura.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Masa maestra salsa secreta, carne de alambre, mozzarella",
                            Nombre = "Zapopina",
                            RutaImagen = "/images/pizzas/zapopina.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Masa maestra, salsa secreta, queso chihuaha, queso monterrey jack, queso cheddar, queso asadero, queso mozzarela",
                            Nombre = "Chicuelina",
                            RutaImagen = "/images/pizzas/chicuelina.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Masa maestra, salsa secreta, carne al pastor, mozzarella",
                            Nombre = "San Fermin",
                            RutaImagen = "/images/pizzas/san_fermin.jpg"
                        });
                });

            modelBuilder.Entity("PizzeriaOnline.Models.Tamaño", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dimensiones")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximoSabores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroRebanadas")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tamaño");
                });

            modelBuilder.Entity("PizzeriaOnline.Models.VariantePizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PizzaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TamañoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.HasIndex("TamañoId");

                    b.ToTable("VariantePizza");
                });

            modelBuilder.Entity("PizzeriaOnline.Models.Ingredientes", b =>
                {
                    b.HasOne("PizzeriaOnline.Models.Pizza", null)
                        .WithMany("Ingredientes")
                        .HasForeignKey("PizzaId");
                });

            modelBuilder.Entity("PizzeriaOnline.Models.VariantePizza", b =>
                {
                    b.HasOne("PizzeriaOnline.Models.Pizza", "Pizza")
                        .WithMany("Variantes")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzeriaOnline.Models.Tamaño", "Tamaño")
                        .WithMany("Variantes")
                        .HasForeignKey("TamañoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pizza");

                    b.Navigation("Tamaño");
                });

            modelBuilder.Entity("PizzeriaOnline.Models.Pizza", b =>
                {
                    b.Navigation("Ingredientes");

                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("PizzeriaOnline.Models.Tamaño", b =>
                {
                    b.Navigation("Variantes");
                });
#pragma warning restore 612, 618
        }
    }
}
