// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzeriaOnline.Data;

#nullable disable

namespace PizzeriaOnline.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("PizzeriaOnline.Models.Ingredientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("PizzeriaOnline.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaImagen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Masa maestra, salsa secreta, aceitunas negras, morrón, elote, cebolla morada, pepperoni, piña, champiñones, romero, mozzarella",
                            Nombre = "Monumental",
                            RutaImagen = "/images/pizzas/monumental.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Masa maestra, salsa secreta, queso mozzarella, albhaca fresca.",
                            Nombre = "Macarena",
                            RutaImagen = "/images/pizzas/macarena.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Masa maestra, salsa secreta, piña, jamón, mozzarella",
                            Nombre = "Sevillana",
                            RutaImagen = "/images/pizzas/sevillana.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Masa maestra, salsa secreta, pepperoni , mozzarella",
                            Nombre = "Manoletina",
                            RutaImagen = "/images/pizzas/manoletina.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Masa maestra, salsa secreta, frijoles, elote, morrón, tocino, chorizo, rodajas de serrano",
                            Nombre = "Miura",
                            RutaImagen = "/images/pizzas/miura.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Masa maestra salsa secreta, carne de alambre, mozzarella",
                            Nombre = "Zapopina",
                            RutaImagen = "/images/pizzas/zapopina.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Masa maestra, salsa secreta, queso chihuaha, queso monterrey jack, queso cheddar, queso asadero, queso mozzarela",
                            Nombre = "Chicuelina",
                            RutaImagen = "/images/pizzas/chicuelina.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Masa maestra, salsa secreta, carne al pastor, mozzarella",
                            Nombre = "San Fermin",
                            RutaImagen = "/images/pizzas/san_fermin.jpg"
                        });
                });

            modelBuilder.Entity("PizzeriaOnline.Models.Tamaño", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dimensiones")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximoSabores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroRebanadas")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tamaños");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dimensiones = "35cm",
                            MaximoSabores = 1,
                            Nombre = "Mediana",
                            NumeroRebanadas = 6,
                            PrecioBase = 150.00m
                        },
                        new
                        {
                            Id = 2,
                            Dimensiones = "40cm",
                            MaximoSabores = 2,
                            Nombre = "Grande",
                            NumeroRebanadas = 8,
                            PrecioBase = 200.00m
                        },
                        new
                        {
                            Id = 3,
                            Dimensiones = "45cm",
                            MaximoSabores = 2,
                            Nombre = "Mediana",
                            NumeroRebanadas = 12,
                            PrecioBase = 250.00m
                        },
                        new
                        {
                            Id = 4,
                            Dimensiones = "50cm",
                            MaximoSabores = 4,
                            Nombre = "Cuadrada",
                            NumeroRebanadas = 16,
                            PrecioBase = 350.00m
                        },
                        new
                        {
                            Id = 5,
                            Dimensiones = "65cm",
                            MaximoSabores = 4,
                            Nombre = "Rectangular",
                            NumeroRebanadas = 24,
                            PrecioBase = 500.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
